# Changes here will be overwritten by Copier
_commit: f8b63c7
_src_path: https://github.com/python-project-templates/base.git
add_extension: rust
email: 3105306+timkpaine@users.noreply.github.com
github: python-project-templates
project_description: A Rust-Python project template
project_name: rust template
python_version_primary: '3.9'
team: Python Project Template Authors
